
; Geometry constants generated by genuine psana

clen =  /LCLS/detector_1/EncoderValue
photon_energy = /LCLS/photon_energy_eV
adu_per_eV = 0.1

data = /entry_1/data_1/data

dim0 = %
dim1 = ss
dim2 = fs

; mask = /entry_1/data_1/mask
; mask_good = 0x0000
; mask_bad = 0xffff

p0a0/fs = +0.999997x +0.001625y -0.001987z
p0a0/ss = +0.001622x -0.999998y -0.001363z
p0a0/res = 10000.000
p0a0/corner_x = -428.896431
p0a0/corner_y = -433.573935
p0a0/coffset = -0.299800
p0a0/min_fs = 0
p0a0/max_fs = 191
p0a0/min_ss = 0
p0a0/max_ss = 175
p0a0/no_index = 0

p0a1/fs = +0.999997x +0.001625y -0.001987z
p0a1/ss = +0.001622x -0.999998y -0.001363z
p0a1/res = 10000.000
p0a1/corner_x = -233.897073
p0a1/corner_y = -433.257148
p0a1/coffset = -0.299838
p0a1/min_fs = 192
p0a1/max_fs = 383
p0a1/min_ss = 0
p0a1/max_ss = 175
p0a1/no_index = 0

p0a2/fs = +0.999997x +0.001625y -0.001987z
p0a2/ss = +0.001622x -0.999998y -0.001363z
p0a2/res = 10000.000
p0a2/corner_x = -428.606121
p0a2/corner_y = -612.573534
p0a2/coffset = -0.299824
p0a2/min_fs = 0
p0a2/max_fs = 191
p0a2/min_ss = 176
p0a2/max_ss = 351
p0a2/no_index = 0

p0a3/fs = +0.999997x +0.001625y -0.001987z
p0a3/ss = +0.001622x -0.999998y -0.001363z
p0a3/res = 10000.000
p0a3/corner_x = -233.606763
p0a3/corner_y = -612.256746
p0a3/coffset = -0.299863
p0a3/min_fs = 192
p0a3/max_fs = 383
p0a3/min_ss = 176
p0a3/max_ss = 351
p0a3/no_index = 0


p1a0/fs = +0.999998x +0.001537y +0.000851z
p1a0/ss = +0.001541x -0.999990y -0.004131z
p1a0/res = 10000.000
p1a0/corner_x = -835.022389
p1a0/corner_y = -435.298380
p1a0/coffset = -0.299746
p1a0/min_fs = 0
p1a0/max_fs = 191
p1a0/min_ss = 352
p1a0/max_ss = 527
p1a0/no_index = 0

p1a1/fs = +0.999998x +0.001537y +0.000851z
p1a1/ss = +0.001541x -0.999990y -0.004131z
p1a1/res = 10000.000
p1a1/corner_x = -640.022690
p1a1/corner_y = -434.998646
p1a1/coffset = -0.299730
p1a1/min_fs = 192
p1a1/max_fs = 383
p1a1/min_ss = 352
p1a1/max_ss = 527
p1a1/no_index = 0

p1a2/fs = +0.999998x +0.001537y +0.000851z
p1a2/ss = +0.001541x -0.999990y -0.004131z
p1a2/res = 10000.000
p1a2/corner_x = -834.746621
p1a2/corner_y = -614.296640
p1a2/coffset = -0.299820
p1a2/min_fs = 0
p1a2/max_fs = 191
p1a2/min_ss = 528
p1a2/max_ss = 703
p1a2/no_index = 0

p1a3/fs = +0.999998x +0.001537y +0.000851z
p1a3/ss = +0.001541x -0.999990y -0.004131z
p1a3/res = 10000.000
p1a3/corner_x = -639.746922
p1a3/corner_y = -613.996906
p1a3/coffset = -0.299804
p1a3/min_fs = 192
p1a3/max_fs = 383
p1a3/min_ss = 528
p1a3/max_ss = 703
p1a3/no_index = 0


p2a0/fs = +0.999980x +0.006183y +0.001290z
p2a0/ss = +0.006182x -0.999981y +0.000650z
p2a0/res = 10000.000
p2a0/corner_x = -433.730418
p2a0/corner_y = -15.506765
p2a0/coffset = -0.300058
p2a0/min_fs = 0
p2a0/max_fs = 191
p2a0/min_ss = 704
p2a0/max_ss = 879
p2a0/no_index = 0

p2a1/fs = +0.999980x +0.006183y +0.001290z
p2a1/ss = +0.006182x -0.999981y +0.000650z
p2a1/res = 10000.000
p2a1/corner_x = -238.734307
p2a1/corner_y = -14.301054
p2a1/coffset = -0.300033
p2a1/min_fs = 192
p2a1/max_fs = 383
p2a1/min_ss = 704
p2a1/max_ss = 879
p2a1/no_index = 0

p2a2/fs = +0.999980x +0.006183y +0.001290z
p2a2/ss = +0.006182x -0.999981y +0.000650z
p2a2/res = 10000.000
p2a2/corner_x = -432.623786
p2a2/corner_y = -194.503307
p2a2/coffset = -0.300047
p2a2/min_fs = 0
p2a2/max_fs = 191
p2a2/min_ss = 880
p2a2/max_ss = 1055
p2a2/no_index = 0

p2a3/fs = +0.999980x +0.006183y +0.001290z
p2a3/ss = +0.006182x -0.999981y +0.000650z
p2a3/res = 10000.000
p2a3/corner_x = -237.627675
p2a3/corner_y = -193.297595
p2a3/coffset = -0.300022
p2a3/min_fs = 192
p2a3/max_fs = 383
p2a3/min_ss = 880
p2a3/max_ss = 1055
p2a3/no_index = 0


p3a0/fs = +0.999996x +0.002986y +0.000098z
p3a0/ss = +0.002986x -0.999995y -0.000844z
p3a0/res = 10000.000
p3a0/corner_x = -838.847597
p3a0/corner_y = -17.667064
p3a0/coffset = -0.299884
p3a0/min_fs = 0
p3a0/max_fs = 191
p3a0/min_ss = 1056
p3a0/max_ss = 1231
p3a0/no_index = 0

p3a1/fs = +0.999996x +0.002986y +0.000098z
p3a1/ss = +0.002986x -0.999995y -0.000844z
p3a1/res = 10000.000
p3a1/corner_x = -643.848467
p3a1/corner_y = -17.084881
p3a1/coffset = -0.299882
p3a1/min_fs = 192
p3a1/max_fs = 383
p3a1/min_ss = 1056
p3a1/max_ss = 1231
p3a1/no_index = 0

p3a2/fs = +0.999996x +0.002986y +0.000098z
p3a2/ss = +0.002986x -0.999995y -0.000844z
p3a2/res = 10000.000
p3a2/corner_x = -838.313168
p3a2/corner_y = -196.666202
p3a2/coffset = -0.299899
p3a2/min_fs = 0
p3a2/max_fs = 191
p3a2/min_ss = 1232
p3a2/max_ss = 1407
p3a2/no_index = 0

p3a3/fs = +0.999996x +0.002986y +0.000098z
p3a3/ss = +0.002986x -0.999995y -0.000844z
p3a3/res = 10000.000
p3a3/corner_x = -643.314038
p3a3/corner_y = -196.084019
p3a3/coffset = -0.299897
p3a3/min_fs = 192
p3a3/max_fs = 383
p3a3/min_ss = 1232
p3a3/max_ss = 1407
p3a3/no_index = 0


p4a0/fs = +0.005265x -0.999986y -0.000500z
p4a0/ss = -0.999986x -0.005265y -0.000711z
p4a0/res = 10000.000
p4a0/corner_x = -423.188699
p4a0/corner_y = 404.929194
p4a0/coffset = -0.299905
p4a0/min_fs = 0
p4a0/max_fs = 191
p4a0/min_ss = 1408
p4a0/max_ss = 1583
p4a0/no_index = 0

p4a1/fs = +0.005265x -0.999986y -0.000500z
p4a1/ss = -0.999986x -0.005265y -0.000711z
p4a1/res = 10000.000
p4a1/corner_x = -422.161967
p4a1/corner_y = 209.931922
p4a1/coffset = -0.299915
p4a1/min_fs = 192
p4a1/max_fs = 383
p4a1/min_ss = 1408
p4a1/max_ss = 1583
p4a1/no_index = 0

p4a2/fs = +0.005265x -0.999986y -0.000500z
p4a2/ss = -0.999986x -0.005265y -0.000711z
p4a2/res = 10000.000
p4a2/corner_x = -602.186173
p4a2/corner_y = 403.986771
p4a2/coffset = -0.299917
p4a2/min_fs = 0
p4a2/max_fs = 191
p4a2/min_ss = 1584
p4a2/max_ss = 1759
p4a2/no_index = 0

p4a3/fs = +0.005265x -0.999986y -0.000500z
p4a3/ss = -0.999986x -0.005265y -0.000711z
p4a3/res = 10000.000
p4a3/corner_x = -601.159441
p4a3/corner_y = 208.989498
p4a3/coffset = -0.299927
p4a3/min_fs = 192
p4a3/max_fs = 383
p4a3/min_ss = 1584
p4a3/max_ss = 1759
p4a3/no_index = 0


p5a0/fs = +0.005465x -0.999985y +0.000009z
p5a0/ss = -0.999977x -0.005465y -0.003911z
p5a0/res = 10000.000
p5a0/corner_x = -425.428767
p5a0/corner_y = 810.064444
p5a0/coffset = -0.299976
p5a0/min_fs = 0
p5a0/max_fs = 191
p5a0/min_ss = 1760
p5a0/max_ss = 1935
p5a0/no_index = 0

p5a1/fs = +0.005465x -0.999985y +0.000009z
p5a1/ss = -0.999977x -0.005465y -0.003911z
p5a1/res = 10000.000
p5a1/corner_x = -424.363066
p5a1/corner_y = 615.067357
p5a1/coffset = -0.299976
p5a1/min_fs = 192
p5a1/max_fs = 383
p5a1/min_ss = 1760
p5a1/max_ss = 1935
p5a1/no_index = 0

p5a2/fs = +0.005465x -0.999985y +0.000009z
p5a2/ss = -0.999977x -0.005465y -0.003911z
p5a2/res = 10000.000
p5a2/corner_x = -604.424725
p5a2/corner_y = 809.086187
p5a2/coffset = -0.300046
p5a2/min_fs = 0
p5a2/max_fs = 191
p5a2/min_ss = 1936
p5a2/max_ss = 2111
p5a2/no_index = 0

p5a3/fs = +0.005465x -0.999985y +0.000009z
p5a3/ss = -0.999977x -0.005465y -0.003911z
p5a3/res = 10000.000
p5a3/corner_x = -603.359025
p5a3/corner_y = 614.089100
p5a3/coffset = -0.300046
p5a3/min_fs = 192
p5a3/max_fs = 383
p5a3/min_ss = 1936
p5a3/max_ss = 2111
p5a3/no_index = 0


p6a0/fs = +0.007984x -0.999968y +0.000179z
p6a0/ss = -0.999968x -0.007984y -0.000326z
p6a0/res = 10000.000
p6a0/corner_x = -5.516605
p6a0/corner_y = 408.947061
p6a0/coffset = -0.300044
p6a0/min_fs = 0
p6a0/max_fs = 191
p6a0/min_ss = 2112
p6a0/max_ss = 2287
p6a0/no_index = 0

p6a1/fs = +0.007984x -0.999968y +0.000179z
p6a1/ss = -0.999968x -0.007984y -0.000326z
p6a1/res = 10000.000
p6a1/corner_x = -3.959683
p6a1/corner_y = 213.953280
p6a1/coffset = -0.300040
p6a1/min_fs = 192
p6a1/max_fs = 383
p6a1/min_ss = 2112
p6a1/max_ss = 2287
p6a1/no_index = 0

p6a2/fs = +0.007984x -0.999968y +0.000179z
p6a2/ss = -0.999968x -0.007984y -0.000326z
p6a2/res = 10000.000
p6a2/corner_x = -184.510890
p6a2/corner_y = 407.517877
p6a2/coffset = -0.300050
p6a2/min_fs = 0
p6a2/max_fs = 191
p6a2/min_ss = 2288
p6a2/max_ss = 2463
p6a2/no_index = 0

p6a3/fs = +0.007984x -0.999968y +0.000179z
p6a3/ss = -0.999968x -0.007984y -0.000326z
p6a3/res = 10000.000
p6a3/corner_x = -182.953968
p6a3/corner_y = 212.524095
p6a3/coffset = -0.300046
p6a3/min_fs = 192
p6a3/max_fs = 383
p6a3/min_ss = 2288
p6a3/max_ss = 2463
p6a3/no_index = 0


p7a0/fs = +0.006549x -0.999978y -0.000898z
p7a0/ss = -0.999978x -0.006548y -0.001341z
p7a0/res = 10000.000
p7a0/corner_x = -7.397898
p7a0/corner_y = 813.224731
p7a0/coffset = -0.300033
p7a0/min_fs = 0
p7a0/max_fs = 191
p7a0/min_ss = 2464
p7a0/max_ss = 2639
p7a0/no_index = 0

p7a1/fs = +0.006549x -0.999978y -0.000898z
p7a1/ss = -0.999978x -0.006548y -0.001341z
p7a1/res = 10000.000
p7a1/corner_x = -6.120856
p7a1/corner_y = 618.228992
p7a1/coffset = -0.300050
p7a1/min_fs = 192
p7a1/max_fs = 383
p7a1/min_ss = 2464
p7a1/max_ss = 2639
p7a1/no_index = 0

p7a2/fs = +0.006549x -0.999978y -0.000898z
p7a2/ss = -0.999978x -0.006548y -0.001341z
p7a2/res = 10000.000
p7a2/corner_x = -186.393900
p7a2/corner_y = 812.052688
p7a2/coffset = -0.300057
p7a2/min_fs = 0
p7a2/max_fs = 191
p7a2/min_ss = 2640
p7a2/max_ss = 2815
p7a2/no_index = 0

p7a3/fs = +0.006549x -0.999978y -0.000898z
p7a3/ss = -0.999978x -0.006548y -0.001341z
p7a3/res = 10000.000
p7a3/corner_x = -185.116857
p7a3/corner_y = 617.056948
p7a3/coffset = -0.300074
p7a3/min_fs = 192
p7a3/max_fs = 383
p7a3/min_ss = 2640
p7a3/max_ss = 2815
p7a3/no_index = 0


p8a0/fs = -0.999999x -0.001159y +0.000081z
p8a0/ss = -0.001159x +0.999999y +0.000454z
p8a0/res = 10000.000
p8a0/corner_x = 416.244988
p8a0/corner_y = 397.093804
p8a0/coffset = -0.300035
p8a0/min_fs = 0
p8a0/max_fs = 191
p8a0/min_ss = 2816
p8a0/max_ss = 2991
p8a0/no_index = 0

p8a1/fs = -0.999999x -0.001159y +0.000081z
p8a1/ss = -0.001159x +0.999999y +0.000454z
p8a1/res = 10000.000
p8a1/corner_x = 221.245120
p8a1/corner_y = 396.867819
p8a1/coffset = -0.300033
p8a1/min_fs = 192
p8a1/max_fs = 383
p8a1/min_ss = 2816
p8a1/max_ss = 2991
p8a1/no_index = 0

p8a2/fs = -0.999999x -0.001159y +0.000081z
p8a2/ss = -0.001159x +0.999999y +0.000454z
p8a2/res = 10000.000
p8a2/corner_x = 416.037552
p8a2/corner_y = 576.093666
p8a2/coffset = -0.300026
p8a2/min_fs = 0
p8a2/max_fs = 191
p8a2/min_ss = 2992
p8a2/max_ss = 3167
p8a2/no_index = 0

p8a3/fs = -0.999999x -0.001159y +0.000081z
p8a3/ss = -0.001159x +0.999999y +0.000454z
p8a3/res = 10000.000
p8a3/corner_x = 221.037684
p8a3/corner_y = 575.867681
p8a3/coffset = -0.300025
p8a3/min_fs = 192
p8a3/max_fs = 383
p8a3/min_ss = 2992
p8a3/max_ss = 3167
p8a3/no_index = 0


p9a0/fs = -0.999990x -0.003010y -0.003361z
p9a0/ss = -0.003007x +0.999995y -0.000678z
p9a0/res = 10000.000
p9a0/corner_x = 824.540342
p9a0/corner_y = 398.941702
p9a0/coffset = -0.300042
p9a0/min_fs = 0
p9a0/max_fs = 191
p9a0/min_ss = 3168
p9a0/max_ss = 3343
p9a0/no_index = 0

p9a1/fs = -0.999990x -0.003010y -0.003361z
p9a1/ss = -0.003007x +0.999995y -0.000678z
p9a1/res = 10000.000
p9a1/corner_x = 629.542327
p9a1/corner_y = 398.354822
p9a1/coffset = -0.300108
p9a1/min_fs = 192
p9a1/max_fs = 383
p9a1/min_ss = 3168
p9a1/max_ss = 3343
p9a1/no_index = 0

p9a2/fs = -0.999990x -0.003010y -0.003361z
p9a2/ss = -0.003007x +0.999995y -0.000678z
p9a2/res = 10000.000
p9a2/corner_x = 824.002021
p9a2/corner_y = 577.940851
p9a2/coffset = -0.300054
p9a2/min_fs = 0
p9a2/max_fs = 191
p9a2/min_ss = 3344
p9a2/max_ss = 3519
p9a2/no_index = 0

p9a3/fs = -0.999990x -0.003010y -0.003361z
p9a3/ss = -0.003007x +0.999995y -0.000678z
p9a3/res = 10000.000
p9a3/corner_x = 629.004006
p9a3/corner_y = 577.353971
p9a3/coffset = -0.300120
p9a3/min_fs = 192
p9a3/max_fs = 383
p9a3/min_ss = 3344
p9a3/max_ss = 3519
p9a3/no_index = 0


p10a0/fs = -0.999974x -0.005463y +0.004748z
p10a0/ss = -0.005458x +0.999984y +0.001247z
p10a0/res = 10000.000
p10a0/corner_x = 422.140923
p10a0/corner_y = -21.872795
p10a0/coffset = -0.300236
p10a0/min_fs = 0
p10a0/max_fs = 191
p10a0/min_ss = 3520
p10a0/max_ss = 3695
p10a0/no_index = 0

p10a1/fs = -0.999974x -0.005463y +0.004748z
p10a1/ss = -0.005458x +0.999984y +0.001247z
p10a1/res = 10000.000
p10a1/corner_x = 227.146032
p10a1/corner_y = -22.938153
p10a1/coffset = -0.300143
p10a1/min_fs = 192
p10a1/max_fs = 383
p10a1/min_ss = 3520
p10a1/max_ss = 3695
p10a1/no_index = 0

p10a2/fs = -0.999974x -0.005463y +0.004748z
p10a2/ss = -0.005458x +0.999984y +0.001247z
p10a2/res = 10000.000
p10a2/corner_x = 421.164029
p10a2/corner_y = 157.124400
p10a2/coffset = -0.300213
p10a2/min_fs = 0
p10a2/max_fs = 191
p10a2/min_ss = 3696
p10a2/max_ss = 3871
p10a2/no_index = 0

p10a3/fs = -0.999974x -0.005463y +0.004748z
p10a3/ss = -0.005458x +0.999984y +0.001247z
p10a3/res = 10000.000
p10a3/corner_x = 226.169137
p10a3/corner_y = 156.059042
p10a3/coffset = -0.300121
p10a3/min_fs = 192
p10a3/max_fs = 383
p10a3/min_ss = 3696
p10a3/max_ss = 3871
p10a3/no_index = 0


p11a0/fs = -0.999982x -0.005992y -0.000071z
p11a0/ss = -0.005992x +0.999980y -0.001788z
p11a0/res = 10000.000
p11a0/corner_x = 825.747098
p11a0/corner_y = -18.930080
p11a0/coffset = -0.300032
p11a0/min_fs = 0
p11a0/max_fs = 191
p11a0/min_ss = 3872
p11a0/max_ss = 4047
p11a0/no_index = 0

p11a1/fs = -0.999982x -0.005992y -0.000071z
p11a1/ss = -0.005992x +0.999980y -0.001788z
p11a1/res = 10000.000
p11a1/corner_x = 630.750599
p11a1/corner_y = -20.098524
p11a1/coffset = -0.300033
p11a1/min_fs = 192
p11a1/max_fs = 383
p11a1/min_ss = 3872
p11a1/max_ss = 4047
p11a1/no_index = 0

p11a2/fs = -0.999982x -0.005992y -0.000071z
p11a2/ss = -0.005992x +0.999980y -0.001788z
p11a2/res = 10000.000
p11a2/corner_x = 824.674551
p11a2/corner_y = 160.066421
p11a2/coffset = -0.300064
p11a2/min_fs = 0
p11a2/max_fs = 191
p11a2/min_ss = 4048
p11a2/max_ss = 4223
p11a2/no_index = 0

p11a3/fs = -0.999982x -0.005992y -0.000071z
p11a3/ss = -0.005992x +0.999980y -0.001788z
p11a3/res = 10000.000
p11a3/corner_x = 629.678052
p11a3/corner_y = 158.897977
p11a3/coffset = -0.300065
p11a3/min_fs = 192
p11a3/max_fs = 383
p11a3/min_ss = 4048
p11a3/max_ss = 4223
p11a3/no_index = 0


p12a0/fs = -0.001639x +0.999995y +0.002645z
p12a0/ss = +0.999999x +0.001638y +0.000522z
p12a0/res = 10000.000
p12a0/corner_x = 411.296591
p12a0/corner_y = -444.278927
p12a0/coffset = -0.300095
p12a0/min_fs = 0
p12a0/max_fs = 191
p12a0/min_ss = 4224
p12a0/max_ss = 4399
p12a0/no_index = 0

p12a1/fs = -0.001639x +0.999995y +0.002645z
p12a1/ss = +0.999999x +0.001638y +0.000522z
p12a1/res = 10000.000
p12a1/corner_x = 410.976983
p12a1/corner_y = -249.279871
p12a1/coffset = -0.300044
p12a1/min_fs = 192
p12a1/max_fs = 383
p12a1/min_ss = 4224
p12a1/max_ss = 4399
p12a1/no_index = 0

p12a2/fs = -0.001639x +0.999995y +0.002645z
p12a2/ss = +0.999999x +0.001638y +0.000522z
p12a2/res = 10000.000
p12a2/corner_x = 590.296326
p12a2/corner_y = -443.985791
p12a2/coffset = -0.300086
p12a2/min_fs = 0
p12a2/max_fs = 191
p12a2/min_ss = 4400
p12a2/max_ss = 4575
p12a2/no_index = 0

p12a3/fs = -0.001639x +0.999995y +0.002645z
p12a3/ss = +0.999999x +0.001638y +0.000522z
p12a3/res = 10000.000
p12a3/corner_x = 589.976719
p12a3/corner_y = -248.986734
p12a3/coffset = -0.300034
p12a3/min_fs = 192
p12a3/max_fs = 383
p12a3/min_ss = 4400
p12a3/max_ss = 4575
p12a3/no_index = 0


p13a0/fs = -0.002216x +0.999998y -0.000206z
p13a0/ss = +0.999991x +0.002216y -0.003502z
p13a0/res = 10000.000
p13a0/corner_x = 413.449291
p13a0/corner_y = -849.741700
p13a0/coffset = -0.299849
p13a0/min_fs = 0
p13a0/max_fs = 191
p13a0/min_ss = 4576
p13a0/max_ss = 4751
p13a0/no_index = 0

p13a1/fs = -0.002216x +0.999998y -0.000206z
p13a1/ss = +0.999991x +0.002216y -0.003502z
p13a1/res = 10000.000
p13a1/corner_x = 413.017087
p13a1/corner_y = -654.742183
p13a1/coffset = -0.299853
p13a1/min_fs = 192
p13a1/max_fs = 383
p13a1/min_ss = 4576
p13a1/max_ss = 4751
p13a1/no_index = 0

p13a2/fs = -0.002216x +0.999998y -0.000206z
p13a2/ss = +0.999991x +0.002216y -0.003502z
p13a2/res = 10000.000
p13a2/corner_x = 592.447754
p13a2/corner_y = -849.345090
p13a2/coffset = -0.299912
p13a2/min_fs = 0
p13a2/max_fs = 191
p13a2/min_ss = 4752
p13a2/max_ss = 4927
p13a2/no_index = 0

p13a3/fs = -0.002216x +0.999998y -0.000206z
p13a3/ss = +0.999991x +0.002216y -0.003502z
p13a3/res = 10000.000
p13a3/corner_x = 592.015550
p13a3/corner_y = -654.345574
p13a3/coffset = -0.299916
p13a3/min_fs = 192
p13a3/max_fs = 383
p13a3/min_ss = 4752
p13a3/max_ss = 4927
p13a3/no_index = 0


p14a0/fs = -0.006384x +0.999980y +0.000458z
p14a0/ss = +0.999979x +0.006385y -0.000706z
p14a0/res = 10000.000
p14a0/corner_x = -6.734160
p14a0/corner_y = -447.626142
p14a0/coffset = -0.300089
p14a0/min_fs = 0
p14a0/max_fs = 191
p14a0/min_ss = 4928
p14a0/max_ss = 5103
p14a0/no_index = 0

p14a1/fs = -0.006384x +0.999980y +0.000458z
p14a1/ss = +0.999979x +0.006385y -0.000706z
p14a1/res = 10000.000
p14a1/corner_x = -7.979117
p14a1/corner_y = -252.630136
p14a1/coffset = -0.300080
p14a1/min_fs = 192
p14a1/max_fs = 383
p14a1/min_ss = 4928
p14a1/max_ss = 5103
p14a1/no_index = 0

p14a2/fs = -0.006384x +0.999980y +0.000458z
p14a2/ss = +0.999979x +0.006385y -0.000706z
p14a2/res = 10000.000
p14a2/corner_x = 172.262147
p14a2/corner_y = -446.483277
p14a2/coffset = -0.300102
p14a2/min_fs = 0
p14a2/max_fs = 191
p14a2/min_ss = 5104
p14a2/max_ss = 5279
p14a2/no_index = 0

p14a3/fs = -0.006384x +0.999980y +0.000458z
p14a3/ss = +0.999979x +0.006385y -0.000706z
p14a3/res = 10000.000
p14a3/corner_x = 171.017190
p14a3/corner_y = -251.487272
p14a3/coffset = -0.300093
p14a3/min_fs = 192
p14a3/max_fs = 383
p14a3/min_ss = 5104
p14a3/max_ss = 5279
p14a3/no_index = 0


p15a0/fs = -0.004511x +0.999990y -0.000094z
p15a0/ss = +0.999989x +0.004511y +0.001212z
p15a0/res = 10000.000
p15a0/corner_x = -6.117373
p15a0/corner_y = -850.236568
p15a0/coffset = -0.299968
p15a0/min_fs = 0
p15a0/max_fs = 191
p15a0/min_ss = 5280
p15a0/max_ss = 5455
p15a0/no_index = 0

p15a1/fs = -0.004511x +0.999990y -0.000094z
p15a1/ss = +0.999989x +0.004511y +0.001212z
p15a1/res = 10000.000
p15a1/corner_x = -6.997091
p15a1/corner_y = -655.238553
p15a1/coffset = -0.299969
p15a1/min_fs = 192
p15a1/max_fs = 383
p15a1/min_ss = 5280
p15a1/max_ss = 5455
p15a1/no_index = 0

p15a2/fs = -0.004511x +0.999990y -0.000094z
p15a2/ss = +0.999989x +0.004511y +0.001212z
p15a2/res = 10000.000
p15a2/corner_x = 172.880674
p15a2/corner_y = -849.429012
p15a2/coffset = -0.299946
p15a2/min_fs = 0
p15a2/max_fs = 191
p15a2/min_ss = 5456
p15a2/max_ss = 5631
p15a2/no_index = 0

p15a3/fs = -0.004511x +0.999990y -0.000094z
p15a3/ss = +0.999989x +0.004511y +0.001212z
p15a3/res = 10000.000
p15a3/corner_x = 172.000955
p15a3/corner_y = -654.430997
p15a3/coffset = -0.299948
p15a3/min_fs = 192
p15a3/max_fs = 383
p15a3/min_ss = 5456
p15a3/max_ss = 5631
p15a3/no_index = 0
